version: '3.8'

services:
  db:
    image: postgres:14
    container_name: modumart_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: modumart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"


volumes:
  postgres_data: